use_frameworks!

target 'kubakbtsheet_Example' do
  pod 'kubakbtsheet', :path => '../'
  
  target 'kubakbtsheet_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
